# Generated by Django 2.2.12 on 2021-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm1A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=60)),
                ('stream', models.CharField(max_length=30)),
            ],
        ),
    ]
